version: '3.1'

services:

  mongo:
    image: mongo:4.0.28-xenial
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - local_mongo_data:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  hotel-rezerv:
    image: sadagatasgarov/hotel-rezerv
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_NAME: hotel-rezervation
      HTTP_LISTENING_PORT: :5000
      JWT_SECRET: bunuAYRIbirYERDEsaxlamaqLAZIMDIR
      MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  local_mongo_data:

